// utils/throwError.js

export const throwError = () => {
    console.log('Error occurred!');
    // Add your error handling logic here
  };
  
